branches:
  only:
    - master
    - dev

skip_tags: true

configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: IEEETalks.sln
  publish_wap: false               # package Web Application Projects (WAP) for Web Deploy
  publish_wap_xcopy: true         # package Web Application Projects (WAP) for XCopy deployment
  publish_azure: false             # package Azure Cloud Service projects and push to artifacts
  publish_nuget: false             # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: false     # generate and publish NuGet symbol packages
  include_nuget_references: false  # add -IncludeReferencedProjects option while packaging NuGet artifacts

  verbosity: detailed

